name: 'retail_sales_etl'
version: '1.0.0'

profile: 'retail_sales_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  retail_sales_etl:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
